import ThemeClient from "./components/themeClient";
import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <ThemeClient attribute="class">
          {children}
        </ThemeClient>
      </body>
    </html>
  )
}
